### ISSUE TITLE
Progress bars increasing at same time/speed for every package

### ISSUE THREAD

**Issue by lucamosca1** [pop-os/cosmic-store#151]
Pre-requisite
Have several packages available to be updated, click update

Actual result
All packages have the progress bar that starts and grow at same time and speed. Not possible to understand the status for a specific package

Video in attachment
[CosmicUpdates.webm](https://github.com/user-attachments/assets/bbf54927-ee4c-4d60-bab0-f4564ae1ba83)

**Comment by lucamosca1** [comment]
Ok, so in this way, isn't better a common progress bar?

**Comment by nalladev** [comment]
<img width="1024" height="698" alt="Image" src="https://github.com/user-attachments/assets/1a4076f1-b08c-496d-9f19-3746943775d0" />

**Comment by MythicHH** [comment]
I think this has been fixed now.

**Comment by nalladev** [comment]
> I think this has been fixed now.

It still occurs for me, but only with Flatpak packages. The two Flatpak updates seem to progress at the same rate, while some system packages are shown as a single bar and progress differently from the other two Flatpak ones.

<img width="1024" height="698" alt="Image" src="https://github.com/user-attachments/assets/03238147-8675-495d-89df-970758e25fcb" />

**Comment by nalladev** [comment]
<img width="1024" height="1017" alt="Image" src="https://github.com/user-attachments/assets/4892eaa0-730d-4fd5-8f22-8198d04ae424" />

Maybe system packages also
