### ISSUE TITLE
Wine mono and wine gecko flatpaks do not update correctly

### ISSUE THREAD

**Issue by Thrackazoid** [pop-os/cosmic-store#422]
When using the update function in cosmic store Wine mono and gecko do not update correctly. Their progress bars go up all the way to 100 then they disappear and they remain in list of packages to be updated. This persists through multiple attempts to update them.

Updating in the terminal via flatpak update does the trick. They vanish from the cosmic store update page afterwards, so it's not a huge problem.

This is the 3rd update where these two specific packages suffer from this bug. It appears that these are the only packages that have this malfunction, or at least the only packages on my system that have this problem.

Running Pop!_OS 24.04 LTS on a darter pro 10 laptop.

**Comment by nalladev** [comment]
<img width="954" height="518" alt="Image" src="https://github.com/user-attachments/assets/75727c93-c7ea-486d-89a7-d484aad0855e" />

Update has no effect when done from the app.
But when running `flatpak update` i get : 
```
~$ flatpak update
Looking for updates…


        ID                              Branch                 Op          Remote           Download
 1. [✓] org.winehq.Wine.gecko           stable-25.08           u           flathub          2.7 kB / 104.0 MB
 2. [✓] org.winehq.Wine.mono            stable-25.08           u           flathub          2.7 kB / 84.1 MB

Updates complete.
```
And when reloading the app, no updates are shown. (this happened to me twice)

**Comment by Thrackazoid** [comment]
Just writing to confirm this issue still exists as of may 20 2026.

**Comment by usbeehu** [comment]
It's also worth to keep in mind that the Store can't handle any other task than updating packages.
That means if a package is deprecated and there is a replacement package it will not perform the replacement. It isn't even capable of displaying such information. Also if a package reaches EOL it will not inform the user about it. Things like these makes the user need to use the terminal which is kinda defends the purpose of a Store/package manager.

**Comment by nalladev** [comment]
> It's also worth to keep in mind that the Store can't handle any other task than updating packages. That means if a package is deprecated and there is a replacement package it will not perform the replacement. It isn't even capable of displaying such information. Also if a package reaches EOL it will not inform the user about it. Things like these makes the user need to use the terminal which is kinda defends the purpose of a Store/package manager.

@usbeehu Deserves it's own issue?

**Comment by usbeehu** [comment]
It had it's own issue, it seems like it has been solved since.
IIRC the last case for me was Thunderbird's package name change and I think that it was done without user intervention.
But if a runtime package has multiple versions installed and there is an old one that is no longer needed, I think it won't be removed by Cosmic Store. I think I had to remove old versions of Mono and Gecko manually because of this a while ago. I'm not sure that this is an issue specific to these two packages or not.

**Comment by bobcat141** [comment]
It still happens to me. Only running `flatpak update` on the terminal makes them go away.

<details>
<summary>Video evidence</summary>

https://github.com/user-attachments/assets/cc531efa-aff5-4b9f-a9f1-95f3b6d2a65f

</details>
